theme = "catppuccin_mocha"

[editor]
true-color = true
color-modes = true
bufferline = "multiple"

[editor.statusline]
left   = ["mode", "spacer", "version-control", "spacer", "file-name"]
center = []
right  = ["diagnostics", "file-encoding"]
#:wmode-separator = "slanted"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
auto-signature-help = false
display-messages = true

[keys.normal]
Z = {Z = ":write-quit-all!"}
C-s = ":write-all"
C-r = ":config-reload"
C-o = ":config-open"

