#set -g status off
set-option -g status-position top
set -g default-terminal "xterm-256color"
set -as terminal-features ',xterm-256color:RGB'

bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded..."

# Switch between panes using alt + arrow
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Use shift + arrow key to move between windows in a session
bind -n S-Left  previous-window
bind -n S-Right next-window
