# -*- shell-script -*-

# L'ordre d'appel est important
#
for script in environment aliases functions prompt; do
    [ -f $HOME/.config/zsh/$script ] && source $HOME/.config/zsh/$script
    [ -f $HOME/.config/zsh/$script.$OS ] && source $HOME/.config/zsh/$script.$OS
done

plugins=(git macos ruby)
ZSH_THEME="agnoster"
ZSH_DISABLE_COMPFIX="true"
DEFAULT_USER=$USER

source $ZSH/oh-my-zsh.sh
# EOF

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/sylvain/.miniconda/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/sylvain/.miniconda/etc/profile.d/conda.sh" ]; then
        . "/Users/sylvain/.miniconda/etc/profile.d/conda.sh"
    else
        export PATH="/Users/sylvain/.miniconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

